//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryStepsUI.UI {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2021 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class ConfigUIForm {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
     
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("MemoryStepsUI.UI.ConfigUIForm", typeof(ConfigUIForm).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a resource 'btnAddStep.Icon'.
        /// </summary>
        public static System.Drawing.Bitmap btnAddStep_Icon {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject(ResourceNames.btnAddStep_Icon, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'btnLaunchTest.Icon'.
        /// </summary>
        public static System.Drawing.Bitmap btnLaunchTest_Icon {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject(ResourceNames.btnLaunchTest_Icon, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'btnLoadConfig.Icon'.
        /// </summary>
        public static System.Drawing.Bitmap btnLoadConfig_Icon {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject(ResourceNames.btnLoadConfig_Icon, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'btnRemoveStp.Icon'.
        /// </summary>
        public static System.Drawing.Bitmap btnRemoveStp_Icon {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject(ResourceNames.btnRemoveStp_Icon, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'btnSaveConfig.Icon'.
        /// </summary>
        public static System.Drawing.Bitmap btnSaveConfig_Icon {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject(ResourceNames.btnSaveConfig_Icon, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'btnStartManualConfig.Icon'.
        /// </summary>
        public static System.Drawing.Bitmap btnStartManualConfig_Icon {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject(ResourceNames.btnStartManualConfig_Icon, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Looks up a resource 'icons_imageList.ImageStream'.
        /// </summary>
        public static object icons_imageList_ImageStream {
            get {
                return ((object)(ResourceManager.GetObject(ResourceNames.icons_imageList_ImageStream, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'btnAddStep.Icon'.
            /// </summary>
            public const string btnAddStep_Icon = "btnAddStep.Icon";
            
            /// <summary>
            /// Stores the resource name 'btnLaunchTest.Icon'.
            /// </summary>
            public const string btnLaunchTest_Icon = "btnLaunchTest.Icon";
            
            /// <summary>
            /// Stores the resource name 'btnLoadConfig.Icon'.
            /// </summary>
            public const string btnLoadConfig_Icon = "btnLoadConfig.Icon";
            
            /// <summary>
            /// Stores the resource name 'btnRemoveStp.Icon'.
            /// </summary>
            public const string btnRemoveStp_Icon = "btnRemoveStp.Icon";
            
            /// <summary>
            /// Stores the resource name 'btnSaveConfig.Icon'.
            /// </summary>
            public const string btnSaveConfig_Icon = "btnSaveConfig.Icon";
            
            /// <summary>
            /// Stores the resource name 'btnStartManualConfig.Icon'.
            /// </summary>
            public const string btnStartManualConfig_Icon = "btnStartManualConfig.Icon";
            
            /// <summary>
            /// Stores the resource name 'icons_imageList.ImageStream'.
            /// </summary>
            public const string icons_imageList_ImageStream = "icons_imageList.ImageStream";
        }
    }
}
